app: kite-public-mcp-everything
primary_region: dfw
org: personal
vm:
    - cpu_kind: shared
      cpus: 1
      memory_mb: 1024
http_service:
    auto_start_machines: true
    auto_stop_machines: true
    force_https: true
    internal_port: 3001
    processes:
        - web
source:
    type: local
    path: .
build:
    image: jhgaylor/mcp-server-everything:latest
env:
    KITE_ID: public-everything-server
processes:
    web: node dist/streamableHttp.js
