app: kite-public-mcp-text-extractor
primary_region: dfw
org: personal
vm:
    - cpu_kind: shared
      cpus: 1
      memory_mb: 1024
http_service:
    auto_start_machines: true
    auto_stop_machines: true
    force_https: true
    internal_port: 8080
source:
    type: local
    path: .
build:
    image: jhgaylor/mcp-server-text-extractor:latest
env:
    KITE_ID: public-text-extractor-server
    PORT: "8080"
